name: ci

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: GHCR Credential
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build image
        run: |
          docker-compose -f docker-compose.yml build
          # docker build -f ./build/Dockerfile \
          # --build-arg =value_here
          # --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/demoapi:latest .

      - name: push image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/demoapi:latest
