name: ci

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR Credential
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: build image
        run: |
          docker build -f ./build/build.Dockerfile --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/demoapi:latest .

      - name: push image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/demoapi:latest
