name: build and test
on:
  push:
    branches:
      - master
      - staging
      - dev
  pull_request:
    branches:
      - master
      - staging
      - dev

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: run unit test
        run: |
          go test --race ./...
